export default {
  HOME: 'HOME',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  RESET_PASSWORD: 'RESET_PASSWORD',
  HOME_SCREEN: 'HOME_SCREEN',
  CREATE_A_PLAN: 'CREATE_A_PLAN',
  VIEW_SPECIFIC_PLAN: 'VIEW_SPECIFIC_PLAN',
  FUND_PLAN: 'FUND_PLAN',
};
